version: '2'

services:
  base:
    build: Dockers/sentry
    restart: unless-stopped
    env_file:
      - base.env
    environment:
      FORCE_SCRIPT_NAME: ''
      SENTRY_WEB_PORT: '9000'
      SENTRY_EMAIL_HOST: 'postfix'
      SENTRY_DB_NAME: 'postgres'
      SENTRY_DB_USER: 'postgres'
      SENTRY_POSTGRES_HOST: 'postgres'
      SENTRY_POSTGRES_PORT: '5432'
      SENTRY_REDIS_HOST: 'redis'
    volumes:
      - ./data/sentry:/var/lib/sentry/files

  web:
    extends: base
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - postfix
    ports:
      - '9000:9000'

  cron:
    extends: base
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    command: run cron

  worker:
    extends: base
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - postfix
    command: run worker

  postfix:
    image: panubo/postfix
    restart: unless-stopped
    environment:
      MAILNAME: 'mail.sentry.example.com'
      MYNETWORKS: '172.17.0.0/16'

  postgres:
    image: postgres:9.5
    restart: unless-stopped
    volumes:
      - ./Dockers/db:/docker-entrypoint-initdb.d/

  redis:
    image: redis:3.2-alpine
    restart: unless-stopped
